stages:
  - build
  - test

# test:
#   stage: test
#   image: registry.gitlab.com/cookanddrum/fyp-24-s2-19/ring-ct:latest
#   script:
#     - echo "running test"
#     - /app/build/test_rct
  
# django-build:
#   stage: build
#   image: docker:27.0.2
#   services:
#     - docker:27.0.2-dind
  
test:
  stage: test
  image: registry.gitlab.com/cookanddrum/fyp-24-s2-19/evoting-web:latest
  script:
    - echo "running django unit test"
    - python /app/manage.py test myapp.tests.test_urls