stages:
  - build
  - test

# test:
#   stage: test
#   image: registry.gitlab.com/cookanddrum/fyp-24-s2-19/ring-ct:latest
#   script:
#     - echo "running test"
#     - /app/build/test_rct
  
# django-build:
#   stage: build
#   image: docker:27.0.2
#   services:
#     - docker:27.0.2-dind
  
# test:
#   stage: test
#   image: registry.gitlab.com/cookanddrum/fyp-24-s2-19/evoting-web:latest
#   script:
#     - echo "running django unit test"
#     - python /app/manage.py test myapp.tests.test_urls

image: docker:27.0.2

before_script:
  - echo $gitlab_pass | docker login -u $gitlab_cr_user --password-stdin $CI_REGISTRY

services:
  - docker:27.0.2-dind

test:
  stage: test
  script:
    - echo "running test"
    - docker-compose -f evoting/docker-compose.test.yml up --exit-code-from web