# default:
#   image: docker:24.0.5
#   services:
#     - docker:24.0.5-dind

# variables:
#   DOCKER_TLS_CERTDIR: "/certs"

# build:
#   stage: build
#   before_script:
#     - echo "$gitlab_pass" | docker login $CR_REGISTRY --username $gitlab_cr_user --password-stdin
#   script:
#     - docker-compose -f evoting/docker-compose.test.yml up --exit-code-from web

services:
  - name: postgres:15


variables:
  POSTGRES_DB: mydb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  DATABASE_URL: postgres://admin:password@postgres:5432/mydb

before_script:
  # Wait for the PostgreSQL service to be available
  - >
    until pg_isready -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER; do
      echo "Waiting for PostgreSQL to be ready..."
      sleep 1
    done
  # Run migrations
  - python /app/manage.py migrate

test:
  stage: test
  image: registry.gitlab.com/cookanddrum/fyp-24-s2-19/evoting-web:latest
  script:
    - echo "running django unit test"
    - python /app/manage.py test myapp.tests.test_models
  timeout: 5 minutes
