image: registry.gitlab.com/cookanddrum/fyp-24-s2-19/ringct:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test:
  stage: test
  script:
    - pwd
    - ls
    - ./build/test_rct 
  artifacts:
    untracked: false
    when: always
    access: all
    expire_in: 30 days
    paths:
      - test_results.xml
    reports:
      junit: test_results.xml
