image: registry.gitlab.com/cookanddrum/fyp-24-s2-19/ringct:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test:
  stage: test
  script:
    - echo "test stage"
