stages:
  - test


test:
  stage: test
  image: registry.gitlab.com/cookanddrum/fyp-24-s2-19/ringct:latest
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - docker run --name ringct -d registry.gitlab.com/cookanddrum/fyp-24-s2-19/ringct:latest
    - docker exec ringct /bin/bash -c "./build/test_rct"
  after_script:
    - docker stop ringct
    - docker rm ringct
  
