default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"

build:
  stage: build
  before_script:
    - echo "$gitlab_pass" | docker login $DOCKER_REGISTRY --username $gitlab_cr_user --password-stdin
  script:
    - docker-compose -f evoting/docker-compose.test.yml up --exit-code-from web