image: docker:20.10.7

stages:
  - test

services:
  - docker:20.10.7-dind

variables:
  DOCKER_DRIVER: overlay2
  TEST_IMAGE: registry.gitlab.com/cookanddrum/fyp-24-s2-19/ringct:latest

test:
  stage: test
  before_script:
    - docker info
  script:
    - docker pull $TEST_IMAGE
    - docker run --rm $TEST_IMAGE /app/build/test_rct
