# default:
#   image: docker:24.0.5
#   services:
#     - docker:24.0.5-dind

# variables:
#   DOCKER_TLS_CERTDIR: "/certs"

# build:
#   stage: build
#   before_script:
#     - echo "$gitlab_pass" | docker login $CR_REGISTRY --username $gitlab_cr_user --password-stdin
#   script:
#     - docker-compose -f evoting/docker-compose.test.yml up --exit-code-from web

services:
  - name: postgres:15
    alias: djangodb
    # variables:
    #     DJANGO_DB_NAME: mydb
    #     DJANGO_DB_USER: admin
    #     DJANGO_DB_PASSWORD: password
    #     DJANGO_DB_HOST: djangodb
    #     DJANGO_DB_PORT: 5432

variables:
  DJANGO_DB_NAME: mydb
  DJANGO_DB_USER: admin
  DJANGO_DB_PASSWORD: password
  DJANGO_DB_HOST: djangodb
  DJANGO_DB_PORT: 5432
  DATABASE_URL: postgres://admin:password@postgres:5432/mydb

before_script:
  # Wait for the PostgreSQL service to be available
  - >
    until pg_isready -h $DJANGO_DB_HOST -p $DJANGO_DB_PORT -U $DJANGO_DB_USER; do
      echo "Waiting for PostgreSQL to be ready..."
      sleep 1
    done
  # Run migrations
  # - /app/wait-for-postgres.sh "$DJANGO_DB_HOST" "python" "manage.py" "test myapp.tests.test_models" 
  - python /app/manage.py makemigrations
  - python /app/manage.py migrate



test:
  stage: test
  image: registry.gitlab.com/cookanddrum/fyp-24-s2-19/evoting-web:latest
  script:
    - echo "running django unit test"
    - python /app/manage.py test myapp.tests.test_models
  timeout: 5 minutes