version: '3'

services:
  web:
    build: .
    command: ["./wait-for-postgres.sh", "db", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_DB_HOST=db  # Use the service name defined here
      - DJANGO_DB_PORT=5432
    links:
      - db

