version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
    entrypoint: [ "/app/wait-for-postgres.sh" ]
    command: [ "db", "python manage.py runserver 0.0.0.0:8000" ]
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ring-ct
    # develop:
    #   #https://docs.docker.com/compose/file-watch/
    #   watch:
    #     - action: sync
    #       # only watch the django changes
    #       path: ./evoting
    #       target: /app/evoting
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=mydb
      - DJANGO_DB_USER=admin
      - DJANGO_DB_PASSWORD=password
    links:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./dbinit:/dbinit
    # volumes:
    #   - pgdata:/var/lib/postgresql/data

  ring-ct:
    build:
      context: ./ringct
    ports:
      - "50051:50051"

      # volumes:
      #   pgdata:
      #     driver: local
