version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
    entrypoint: [ "/app/wait-for-postgres.sh" ]
    command: [ "djangodb", "python manage.py runserver 0.0.0.0:8000" ]
    ports:
      - "8000:8000"
    depends_on:
      - djangodb
      - ring-ct
    environment:
      - DJANGO_DB_HOST=djangodb
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=mydb
      - DJANGO_DB_USER=admin
      - DJANGO_DB_PASSWORD=password
    links:
      - djangodb

  djangodb:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./dbinit:/dbinit
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
  
  ringct-db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ringct
    ports:
      - "5433:5432"

  ring-ct:
    build:
      context: ./ringct
    depends_on:
      - djangodb
      - ringct-db
    ports:
      - "50051:50051"
    environment:
      - DJANGO_DB_HOST=djangodb
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=mydb
      - DJANGO_DB_USER=admin
      - DJANGO_DB_PASSWORD=password
      - RINGCT_DB_HOST=ringct-db
      - RINGCT_DB_PORT=5432
      - RINGCT_DB_NAME=ringct
      - RINGCT_DB_USER=admin
      - RINGCT_DB_PASSWORD=password
      # volumes:
      #   pgdata:
      #     driver: local
