version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
    entrypoint: [ "/app/wait-for-postgres.sh" ]
    ports:
      - "8000:8000"
    depends_on:
      - djangodb
      - ring-ct
    environment:
      - DATABASE_URL=postgres://admin:password@djangodb:5432/mydb
      - ENVIRONMENT=local
      - RINGCT_URL=ring-ct:50051
      - DJANGO_SECRET_KEY=thisisasecretkeyinlocal
    links:
      - djangodb

  djangodb:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./dbinit:/dbinit
  
  # ringct-db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: ringct
  #   ports:
  #     - "5433:5432"

  ring-ct:
    build:
      context: ./ringct
    depends_on:
      - djangodb
      # - ringct-db
    ports:
      - "50051:50051"
    environment:
      - DJANGO_DB_HOST=djangodb
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=mydb
      - DJANGO_DB_USER=admin
      - DJANGO_DB_PASSWORD=password
      - RINGCT_DB_HOST=ringct-db
      - RINGCT_DB_PORT=5432
      - RINGCT_DB_NAME=ringct
      - RINGCT_DB_USER=admin
      - RINGCT_DB_PASSWORD=password
      - DATABASE_URL=postgres://admin:password@djangodb:5432/mydb
