# Generated by Django 4.2.13 on 2024-05-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('user_id', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=200)),
                ('district', models.CharField(choices=[('yio chu kang', 'Yio Chu Kang'), ('ang mo kio', 'Ang Mo Kio'), ('bishan', 'Bishan')], max_length=100)),
                ('role', models.CharField(choices=[('user', 'User'), ('candidate', 'Candidate'), ('admin', 'Admin')], max_length=50)),
            ],
        ),
    ]
