# Generated by Django 4.2.13 on 2024-08-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singpassuser',
            name='salt',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='webauthncredentials',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
    ]
