# Generated by Django 4.2.13 on 2024-07-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
