# Generated by Django 4.2.13 on 2024-07-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_useraccount_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='webauthncredentials',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
    ]
