# Generated by Django 4.2.13 on 2024-05-18 07:44
from django.db import migrations, models

def add_election_phases(apps, schema_editor):
    ElectionPhase = apps.get_model('myapp', 'ElectionPhase')
    ElectionPhase.objects.create(name='Campaigning Day', is_active=False)
    ElectionPhase.objects.create(name='Cooling Off Day', is_active=False)
    ElectionPhase.objects.create(name='Polling Day', is_active=False)
    ElectionPhase.objects.create(name='End Election', is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_district_alter_useraccount_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(add_election_phases),
    ]
