# Generated by Django 4.2.13 on 2024-08-11 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_singpassuser_salt_useraccount_first_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webauthncredentials',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to='myapp.voter'),
        ),
        migrations.AddField(
            model_name='webauthnregistration',
            name='voter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.voter'),
        ),
        migrations.AlterField(
            model_name='webauthncredentials',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webauthnregistration',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
