# Generated by Django 4.2.13 on 2024-05-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_electionphase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionphase',
            name='description',
        ),
    ]
