# Generated by Django 5.0.4 on 2024-06-02 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_announcement_party_alter_useraccount_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
