# Generated by Django 4.2.13 on 2024-06-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_temporaryvoter'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryvoter',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
